### PR TITLE
Hotfix

### PR DESCRIPTION
**Pull request by siggines**
Forgot to add select
Screenshot from 2021-03-19 17-36-49
^right one is the original _time.sleep_ result

### CODE REVIEW

**Comment by siggines** [comment]
Confusing that I made two pull requests because of making a second branch sorry, just look at first pull-request for screenshot of the timed code with a cleaner example.

**Comment by jakewtaylor** [comment]
Can you elaborate please? 😅

**Comment by siggines** [comment]
> Can you elaborate please?

Importtime with python shows that it takes around 2/3 of the time, and speed is actually useful in python

**Comment by jakewtaylor** [comment]
Thanks but this code has been replaced with some threading stuff instead 🙂

**Pull request closed without merging**
